name: Economist Application
favicon: null
layout_spectrum: 0.65417
typography_spectrum: 0.90362
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f0f0'
    - '#9c9c9c'
    - '#e3120b'
    - '#4a4a4a'
    - '#ea4d48'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
